const translations = {
    it: {
        "tab_player": "Player", "tab_queue": "Coda", "tab_favs": "Preferiti",
        "tab_playlists": "Playlist", "tab_webradio": "Radio", "tab_folders": "File",
        "tab_albums": "Album", "tab_artists": "Artisti", "tab_search": "Cerca", "tab_settings": "Impost.",
        "title_queue_play": "Coda di Riproduzione", "title_playlists_saved": "Le tue Playlist Salvate",
        "title_new_radio": "Configura Nuova Web Radio",
        "hdr_lang": "Lingua", "hdr_conn": "Connessione & Integrazione",
        "hdr_screen": "Gestione Screensaver", "hdr_layout": "Aspetto e Layout",
        "hdr_dsp": "DSP & Audio Processing", "hdr_smart_home": "Smart Home (HA / Alexa)",
        "hdr_appearance": "Aspetto & Screensaver",
        "hdr_backup": "Backup & Ripristino",
        "hw_bass": "BASS", "hw_treble": "TREBLE", "hw_volume": "VOLUME",
        "lbl_camilladsp": "CamillaDSP (Stack)", "desc_camilladsp": "Accendi/Spegni elaborazione audio",
        "desc_smart_home": "Usa questi Endpoint nei tuoi rest_command di Home Assistant per controllare il rack tramite voce.",
        "lbl_endpoint_search": "Endpoint Ricerca Vocale e Play", "lbl_endpoint_camilla": "CamillaDSP ON/OFF",
        "item_folder": "Cartella", "item_track": "Traccia", "item_playlist": "Playlist",
        "item_album": "Album", "item_artist": "Artista", "item_root": "Root",
        "item_webradio_custom": "Web Radio (Custom)", "hdr_webradio_moode": "Web Radio moOde", 
        "hdr_webradio_recent": "Radio Browser (Recenti)", "hdr_webradio_custom": "Stazioni Personalizzate",
        "msg_added_queue": "Aggiunto in coda!", "msg_playing": "In riproduzione...",
        "msg_sync_ok": "Sincronizzazione completata!", "msg_waiting": "In attesa di connessione...",
        "msg_unknown": "Sconosciuto", "msg_loading": "Caricamento in corso...", "msg_empty": "Nessun elemento trovato.",
        "prompt_playlist_name": "Nome playlist:", "msg_playlist_saved": "Playlist salvata!",
        "confirm_delete_playlist": "Eliminare la playlist", "msg_fill_required": "Compila almeno il nome e l'URL",
        "confirm_delete_radio": "Vuoi rimuovere", "msg_sys_error": "Errore nell'esecuzione del comando di sistema.",
        "confirm_sync": "Avviare la sincronizzazione?", "msg_error": "Errore.",
        "msg_error_prefix": "ERRORE: ", "msg_php_error": "ERRORE PHP",
        "msg_stream_url_missing": "Imposta l'URL dello streaming HTTP nelle Impostazioni!",
        "msg_stream_error": "Impossibile connettersi allo stream: ", "confirm_clear_queue": "Svuotare la coda?",
        "msg_network_error": "Errore Rete: Stazione irraggiungibile",
        "msg_offline": "Offline - Rete Assente",
        "sync_title": "Sincronizzazione in corso...", "sync_desc1": "Sto analizzando l'archivio e le copertine sul server.",
        "sync_desc2": "Questa operazione può richiedere un paio di minuti.",
        "btn_sync": "Sincronizza", "btn_save_playlist": "Salva Playlist", "btn_clear": "Svuota",
        "btn_save": "Salva", "btn_up": "Su", "btn_back": "Indietro", "btn_search": "CERCA",
        "btn_space": "SPAZIO", "btn_test_ss": "Prova Screensaver", "btn_close_moode": "Torna al Rack",
        "btn_play": "Play",
        "btn_export": "Esporta Config", "btn_import": "Importa Config",
        "desc_backup": "Salva le tue radio, preferiti e impostazioni in un file locale.",
        "lbl_config_radio": "Configura Nuova Web Radio", "lbl_radio_name": "Nome Stazione", 
        "lbl_radio_url": "URL Stream", "lbl_radio_logo": "URL Logo (Opzionale)", "lbl_custom_radios": "Le tue Web Radio",
        "ph_radio_name": "es. Radio Paradise", "ph_radio_url": "es. http://stream.radioparadise.com/flac",
        "ph_radio_logo": "es. https://.../logo.png", "ph_moode_url": "es. http://192.168.1.50",
        "ph_ws_uri": "es. ws://192.168.1.50:1234", "ph_stream_url": "es. http://192.168.1.50:8000/mpd.ogg",
        "lbl_search_engine": "Motore di Ricerca", "search_any": "Cerca Ovunque (Tutto)", 
        "search_title": "Solo Brani (Titolo)", "search_album": "Solo Album", "search_artist": "Solo Artisti",
        "search_genre": "Solo Genere", "search_file": "Solo Cartelle/Percorsi", "search_radio": "Solo Radio",
        "lbl_settings_sys": "Pannello di Controllo e Integrazioni", "lbl_lang_select": "Seleziona Lingua Interfaccia",
        "lbl_moode_url": "URL Interfaccia moOde Audio", "lbl_ws_uri": "CamillaDSP WebSocket URI",
        "lbl_stream_url": "URL Stream Locale (moOde HTTP)", "lbl_ss_timeout": "Avvio SS",
        "lbl_ss_random": "Rotazione Stili", "lbl_vu_style": "Modello VU Meter (Tema Globale)",
        "lbl_device_layout": "Adattamento Schermo", "lbl_extra_options": "Opzioni UI e Motore Grafico", 
        "lbl_show_inline_vu": "VU Meter nel Player", "lbl_backlight": "Luce Pannello Screensaver", 
        "lbl_local_analyzer": "Analizzatore Audio Locale",
        "lbl_keep_ss_style": "Mantieni tema ruotato all'uscita dal SS",
        
        "vu_blue_mod70": "Blue Classic Mod. 70",
        "vu_blue_mono_mod1000": "Blue Mono Mod. 1000",
        "vu_champagne_mod73": "Champagne Gold Mod. 73",
        "vu_vfd_mod85": "VFD Peak Mod. 85",
        "vu_vintage_mod60": "Studio Vintage Mod. 60",
        "vu_waves_mod99": "Waves Studio Mod. 99",
        "vu_studio_mod77": "Studio Master Mod. 77",
        "vu_dark_meter_mod88": "Dark Meter Mod. 88",
        "vu_british_mod90": "British Console Mod. 90",
        "vu_light_meter_mod88": "Light Meter Mod. 88",
        "vu_cyan_meter_mod88": "Cyan Meter Mod. 88",
        "vu_neon_mod95": "Neon Cyan Mod. 95",
        "vu_minimal_mod00": "Minimal Dark Mod. 00",
        "vu_orange_mod70": "Warm Orange Mod. 70",
        "vu_tube_mod50": "Blue Tube Mod. 50",
        "vu_flat_mod00": "Minimal Flat Mod. 00",
        "vu_touch_mod15": "Touch VU Mod. 15",
        "vu_amber_mod75": "Amber Classic Mod. 75",
        
        "ss_disabled": "Disattivato", "ss_1min": "Dopo 1 Minuto", "ss_5min": "Dopo 5 Minuti", "ss_15min": "Dopo 15 Minuti",
        "ss_fixed": "Fissa", "ss_30sec": "Ogni 30 Sec.", "ss_1min_rot": "Ogni 1 Min.", "ss_5min_rot": "Ogni 5 Min.",
        "layout_auto": "Automatico", "layout_desktop": "1920x1080 o sup.",
        "layout_laptop": "1366x768 (Tablet Oriz.)", "layout_tablet": "800x1280 (Tablet Vert.)", "layout_mobile": "Smartphone",
        "hint_moode": "* Lascialo vuoto per usare l'IP attuale. Verrà aperto cliccando sulla copertina.",
        "hint_ws": "* Di default punta all'indirizzo del rack. Modificalo se CamillaDSP usa un IP o porta diversa.",
        "hint_stream": "* URL del server HTTP di MPD per ascoltare l'audio sul dispositivo.",
        "ss_hint": "Tocca per uscire, Scorri per cambiare VU Meter",
        "tip_repeat": "Ripeti", "tip_prev": "Indietro", "tip_next": "Avanti", "tip_random": "Casuale", 
        "tip_stream": "Ascolta sul dispositivo", "tip_queue": "Vai alla Coda", "tip_mute": "Mute / Unmute",
        "tip_moode": "Apri interfaccia ufficiale moOde Audio", "tip_sync": "Sincronizza Archivio con MPD",
        "tip_change_view": "Cambia Vista", "tip_add_queue": "Aggiungi alla coda",
        "tip_listen": "Ascolta", "tip_favorites": "Preferiti", "tip_edit": "Modifica",
        "tip_delete": "Elimina", "tip_dsp_pause": "Metti in pausa o ferma la musica per accendere/spegnere il DSP.",
        "lbl_mini_player_ss": "Mostra Mini Player nel Salvaschermo",
        "tip_exit_ss": "Esci dal Salvaschermo",
        "alpha_all": "Tutti",
        "hdr_defaults": "Imposta Predefiniti Globali",
        "desc_defaults": "Da qui puoi configurare i valori iniziali che verranno assegnati automaticamente a qualsiasi nuovo dispositivo che aprirà il client per la prima volta.",
        "lbl_vu_style_def": "Modello VU Meter Predefinito (Tema)",
        "lbl_layout_def": "Risoluzione e Adattamento Schermo (Player)",
        "lbl_ss_timeout_def": "Timeout Screensaver Automatico",
        "lbl_ss_random_def": "Rotazione Stili Casuale",
        "btn_save_defaults": "Salva come Predefinito per i Nuovi Client",
        "hdr_diagnostics": "Diagnostica API Bridge",
        "btn_run_tests": "Esegui Nuovamente"
    },
    en: {
        "tab_player": "Player", "tab_queue": "Queue", "tab_favs": "Favorites",
        "tab_playlists": "Playlists", "tab_webradio": "Radio", "tab_folders": "Files",
        "tab_albums": "Albums", "tab_artists": "Artists", "tab_search": "Search", "tab_settings": "Settings",
        "title_queue_play": "Playback Queue", "title_playlists_saved": "Your Saved Playlists",
        "title_new_radio": "Configure New Web Radio",
        "hdr_lang": "Language", "hdr_conn": "Connection & Integration",
        "hdr_screen": "Screensaver Management", "hdr_layout": "Appearance & Layout",
        "hdr_dsp": "DSP & Audio Processing", "hdr_smart_home": "Smart Home (HA / Alexa)",
        "hdr_appearance": "Appearance & Screensaver",
        "hdr_backup": "Backup & Restore",
        "hw_bass": "BASS", "hw_treble": "TREBLE", "hw_volume": "VOLUME",
        "lbl_camilladsp": "CamillaDSP (Stack)", "desc_camilladsp": "Turn audio processing on/off",
        "desc_smart_home": "Use these Endpoints in your Home Assistant rest_command to control the rack via voice.",
        "lbl_endpoint_search": "Voice Search & Play Endpoint", "lbl_endpoint_camilla": "CamillaDSP ON/OFF Endpoint",
        "item_folder": "Folder", "item_track": "Track", "item_playlist": "Playlist",
        "item_album": "Album", "item_artist": "Artist", "item_root": "Root",
        "item_webradio_custom": "Web Radio (Custom)", "hdr_webradio_moode": "moOde Web Radio", 
        "hdr_webradio_recent": "Radio Browser (Recent)", "hdr_webradio_custom": "Custom Stations",
        "msg_added_queue": "Added to queue!", "msg_playing": "Playing...",
        "msg_sync_ok": "Sync completed successfully!", "msg_waiting": "Waiting for connection...",
        "msg_unknown": "Unknown", "msg_loading": "Loading...", "msg_empty": "No items found.",
        "prompt_playlist_name": "Playlist name:", "msg_playlist_saved": "Playlist saved!",
        "confirm_delete_playlist": "Delete playlist", "msg_fill_required": "Please fill in at least the name and URL",
        "confirm_delete_radio": "Do you want to remove", "msg_sys_error": "Error executing system command.",
        "confirm_sync": "Start synchronization?", "msg_error": "Error.",
        "msg_error_prefix": "ERROR: ", "msg_php_error": "PHP ERROR",
        "msg_stream_url_missing": "Set the HTTP streaming URL in Settings!",
        "msg_stream_error": "Unable to connect to stream: ", "confirm_clear_queue": "Clear the queue?",
        "msg_network_error": "Network Error: Station unreachable",
        "msg_offline": "Offline - No Network",
        "sync_title": "Syncing in progress...", "sync_desc1": "Analyzing archive and covers on the server.",
        "sync_desc2": "This operation may take a couple of minutes.",
        "btn_sync": "Sync", "btn_save_playlist": "Save Playlist", "btn_clear": "Clear",
        "btn_save": "Save", "btn_up": "Up", "btn_back": "Back", "btn_search": "SEARCH",
        "btn_space": "SPACE", "btn_test_ss": "Test Screensaver", "btn_close_moode": "Back to Rack",
        "btn_play": "Play",
        "btn_export": "Export Config", "btn_import": "Import Config",
        "desc_backup": "Save your radios, favorites, and settings to a local file.",
        "lbl_config_radio": "Configure New Web Radio", "lbl_radio_name": "Station Name", 
        "lbl_radio_url": "Stream URL", "lbl_radio_logo": "Logo URL (Optional)", "lbl_custom_radios": "Your Web Radios",
        "ph_radio_name": "e.g. Radio Paradise", "ph_radio_url": "e.g. http://stream.radioparadise.com/flac",
        "ph_radio_logo": "e.g. https://.../logo.png", "ph_moode_url": "e.g. http://192.168.1.50",
        "ph_ws_uri": "e.g. ws://192.168.1.50:1234", "ph_stream_url": "e.g. http://192.168.1.50:8000/mpd.ogg",
        "lbl_search_engine": "Search Engine", "search_any": "Search Everywhere (All)", 
        "search_title": "Tracks Only (Title)", "search_album": "Albums Only", "search_artist": "Artists Only",
        "search_genre": "Genre Only", "search_file": "Folders/Paths Only", "search_radio": "Radio Only",
        "lbl_settings_sys": "Control Panel & Integrations", "lbl_lang_select": "Interface Language",
        "lbl_moode_url": "moOde Audio UI URL", "lbl_ws_uri": "CamillaDSP WebSocket URI",
        "lbl_stream_url": "Local Stream URL (moOde HTTP)", "lbl_ss_timeout": "Start SS",
        "lbl_ss_random": "Style Rotation", "lbl_vu_style": "VU Meter Model (Global Theme)",
        "lbl_device_layout": "Screen Adaptation", "lbl_extra_options": "UI & Graphics Engine Options", 
        "lbl_show_inline_vu": "VU Meter in Player", "lbl_backlight": "Screensaver Panel Backlight", 
        "lbl_local_analyzer": "Local Audio Analyzer",
        "lbl_keep_ss_style": "Keep rotated theme on SS exit",
        
        "vu_blue_mod70": "Blue Classic Mod. 70",
        "vu_blue_mono_mod1000": "Blue Mono Mod. 1000",
        "vu_champagne_mod73": "Champagne Gold Mod. 73",
        "vu_vfd_mod85": "VFD Peak Mod. 85",
        "vu_vintage_mod60": "Studio Vintage Mod. 60",
        "vu_waves_mod99": "Waves Studio Mod. 99",
        "vu_studio_mod77": "Studio Master Mod. 77",
        "vu_dark_meter_mod88": "Dark Meter Mod. 88",
        "vu_british_mod90": "British Console Mod. 90",
        "vu_light_meter_mod88": "Light Meter Mod. 88",
        "vu_cyan_meter_mod88": "Cyan Meter Mod. 88",
        "vu_neon_mod95": "Neon Cyan Mod. 95",
        "vu_minimal_mod00": "Minimal Dark Mod. 00",
        "vu_orange_mod70": "Warm Orange Mod. 70",
        "vu_tube_mod50": "Blue Tube Mod. 50",
        "vu_flat_mod00": "Minimal Flat Mod. 00",
        "vu_touch_mod15": "Touch VU Mod. 15",
        "vu_amber_mod75": "Amber Classic Mod. 75",

        "ss_disabled": "Disabled", "ss_1min": "After 1 Minute", "ss_5min": "After 5 Minutes", "ss_15min": "After 15 Minutes",
        "ss_fixed": "Fixed", "ss_30sec": "Every 30 Sec.", "ss_1min_rot": "Every 1 Min.", "ss_5min_rot": "Every 5 Min.",
        "layout_auto": "Automatic", "layout_desktop": "1920x1080 or above",
        "layout_laptop": "1366x768 (Horiz. Tablet)", "layout_tablet": "800x1280 (Vert. Tablet)", "layout_mobile": "Smartphone",
        "hint_moode": "* Leave blank to use current IP. Will open when clicking on the cover.",
        "hint_ws": "* Defaults to rack address. Modify if CamillaDSP uses a different IP or port.",
        "hint_stream": "* MPD HTTP server URL to listen to audio on device.",
        "ss_hint": "Tap to exit, Swipe to change VU Meter",
        "tip_repeat": "Repeat", "tip_prev": "Previous", "tip_next": "Next", "tip_random": "Random", 
        "tip_stream": "Listen on device", "tip_queue": "Go to Queue", "tip_mute": "Mute / Unmute",
        "tip_moode": "Open official moOde Audio UI", "tip_sync": "Sync Library with MPD",
        "tip_change_view": "Change View", "tip_add_queue": "Add to Queue",
        "tip_listen": "Listen", "tip_favorites": "Favorites", "tip_edit": "Edit",
        "tip_delete": "Delete", "tip_dsp_pause": "Pause or stop the music to toggle the DSP.",
        "lbl_mini_player_ss": "Show Mini Player in Screensaver",
        "tip_exit_ss": "Exit Screensaver",
        "alpha_all": "All",
        "hdr_defaults": "Set Global Defaults",
        "desc_defaults": "Configure the initial values automatically assigned to any new device opening the client for the first time.",
        "lbl_vu_style_def": "Default VU Meter Model (Theme)",
        "lbl_layout_def": "Screen Resolution and Adaptation (Player)",
        "lbl_ss_timeout_def": "Auto Screensaver Timeout",
        "lbl_ss_random_def": "Random Style Rotation",
        "btn_save_defaults": "Save as Default for New Clients",
        "hdr_diagnostics": "API Bridge Diagnostics",
        "btn_run_tests": "Run Again"
    },
    es: {
        "tab_player": "Reproductor", "tab_queue": "Cola", "tab_favs": "Favoritos",
        "tab_playlists": "Listas", "tab_webradio": "Radio", "tab_folders": "Archivos",
        "tab_albums": "Álbumes", "tab_artists": "Artistas", "tab_search": "Buscar", "tab_settings": "Ajustes",
        "title_queue_play": "Cola de Reproducción", "title_playlists_saved": "Tus Listas Guardadas",
        "title_new_radio": "Configurar Nueva Web Radio",
        "hdr_lang": "Idioma", "hdr_conn": "Conexión e Integración",
        "hdr_screen": "Gestión de Salvapantallas", "hdr_layout": "Apariencia y Diseño",
        "hdr_dsp": "DSP y Procesamiento de Audio", "hdr_smart_home": "Smart Home (HA / Alexa)",
        "hdr_appearance": "Apariencia y Salvapantallas",
        "hdr_backup": "Copia de Seguridad y Restauración",
        "hw_bass": "GRAVES", "hw_treble": "AGUDOS", "hw_volume": "VOLUMEN",
        "lbl_camilladsp": "CamillaDSP (Stack)", "desc_camilladsp": "Activar/Desactivar procesamiento de audio",
        "desc_smart_home": "Usa estos endpoints en tus rest_command de Home Assistant para controlar el rack por voz.",
        "lbl_endpoint_search": "Endpoint de Búsqueda por Voz y Reproducción", "lbl_endpoint_camilla": "Endpoint CamillaDSP ON/OFF",
        "item_folder": "Carpeta", "item_track": "Pista", "item_playlist": "Lista",
        "item_album": "Álbum", "item_artist": "Artista", "item_root": "Raíz",
        "item_webradio_custom": "Web Radio (Personalizada)", "hdr_webradio_moode": "Web Radio moOde", 
        "hdr_webradio_recent": "Radio Browser (Recientes)", "hdr_webradio_custom": "Emisoras Personalizadas",
        "msg_added_queue": "¡Añadido a la cola!", "msg_playing": "Reproduciendo...",
        "msg_sync_ok": "¡Sincronización completada!", "msg_waiting": "Esperando conexión...",
        "msg_unknown": "Desconocido", "msg_loading": "Cargando...", "msg_empty": "No se encontraron elementos.",
        "prompt_playlist_name": "Nombre de la lista:", "msg_playlist_saved": "¡Lista guardada!",
        "confirm_delete_playlist": "Eliminar lista", "msg_fill_required": "Completa al menos el nombre y la URL",
        "confirm_delete_radio": "¿Deseas eliminar", "msg_sys_error": "Error al ejecutar el comando del sistema.",
        "confirm_sync": "¿Iniciar sincronización?", "msg_error": "Error.",
        "msg_error_prefix": "ERROR: ", "msg_php_error": "ERROR PHP",
        "msg_stream_url_missing": "¡Configura la URL de streaming HTTP en los Ajustes!",
        "msg_stream_error": "Imposible conectar con el stream: ", "confirm_clear_queue": "¿Vaciar la cola?",
        "msg_network_error": "Error de red: Emisora inalcanzable",
        "msg_offline": "Sin conexión - Red no disponible",
        "sync_title": "Sincronización en curso...", "sync_desc1": "Analizando archivo y carátulas en el servidor.",
        "sync_desc2": "Esta operación puede tardar un par de minutos.",
        "btn_sync": "Sincronizar", "btn_save_playlist": "Guardar Lista", "btn_clear": "Vaciar",
        "btn_save": "Guardar", "btn_up": "Arriba", "btn_back": "Atrás", "btn_search": "BUSCAR",
        "btn_space": "ESPACIO", "btn_test_ss": "Probar Salvapantallas", "btn_close_moode": "Volver al Rack",
        "btn_play": "Reproducir",
        "btn_export": "Exportar Config", "btn_import": "Importar Config",
        "desc_backup": "Guarda tus radios, favoritos y ajustes en un archivo local.",
        "lbl_config_radio": "Configurar Nueva Web Radio", "lbl_radio_name": "Nombre de la Emisora", 
        "lbl_radio_url": "URL del Stream", "lbl_radio_logo": "URL del Logo (Opcional)", "lbl_custom_radios": "Tus Web Radios",
        "ph_radio_name": "ej. Radio Paradise", "ph_radio_url": "ej. http://stream.radioparadise.com/flac",
        "ph_radio_logo": "ej. https://.../logo.png", "ph_moode_url": "ej. http://192.168.1.50",
        "ph_ws_uri": "ej. ws://192.168.1.50:1234", "ph_stream_url": "ej. http://192.168.1.50:8000/mpd.ogg",
        "lbl_search_engine": "Motor de Búsqueda", "search_any": "Buscar en Todas Partes", 
        "search_title": "Solo Pistas (Título)", "search_album": "Solo Álbumes", "search_artist": "Solo Artistas",
        "search_genre": "Solo Género", "search_file": "Solo Carpetas/Rutas", "search_radio": "Solo Radio",
        "lbl_settings_sys": "Panel de Control e Integraciones", "lbl_lang_select": "Idioma de la Interfaz",
        "lbl_moode_url": "URL de Interfaz moOde Audio", "lbl_ws_uri": "URI WebSocket de CamillaDSP",
        "lbl_stream_url": "URL de Stream Local (moOde HTTP)", "lbl_ss_timeout": "Inicio de Salvapantallas",
        "lbl_ss_random": "Rotación de Estilos", "lbl_vu_style": "Modelo de VU Meter (Tema Global)",
        "lbl_device_layout": "Adaptación de Pantalla", "lbl_extra_options": "Opciones de UI y Gráficos", 
        "lbl_show_inline_vu": "VU Meter en el Reproductor", "lbl_backlight": "Luz de Panel de Salvapantallas", 
        "lbl_local_analyzer": "Analizador de Audio Local",
        "lbl_keep_ss_style": "Mantener tema rotado al salir del SS",
        
        "vu_blue_mod70": "Blue Classic Mod. 70",
        "vu_blue_mono_mod1000": "Blue Mono Mod. 1000",
        "vu_champagne_mod73": "Champagne Gold Mod. 73",
        "vu_vfd_mod85": "VFD Peak Mod. 85",
        "vu_vintage_mod60": "Studio Vintage Mod. 60",
        "vu_waves_mod99": "Waves Studio Mod. 99",
        "vu_studio_mod77": "Studio Master Mod. 77",
        "vu_dark_meter_mod88": "Dark Meter Mod. 88",
        "vu_british_mod90": "British Console Mod. 90",
        "vu_light_meter_mod88": "Light Meter Mod. 88",
        "vu_cyan_meter_mod88": "Cyan Meter Mod. 88",
        "vu_neon_mod95": "Neon Cyan Mod. 95",
        "vu_minimal_mod00": "Minimal Dark Mod. 00",
        "vu_orange_mod70": "Warm Orange Mod. 70",
        "vu_tube_mod50": "Blue Tube Mod. 50",
        "vu_flat_mod00": "Minimal Flat Mod. 00",
        "vu_touch_mod15": "Touch VU Mod. 15",
        "vu_amber_mod75": "Amber Classic Mod. 75",

        "ss_disabled": "Desactivado", "ss_1min": "Después de 1 Minuto", "ss_5min": "Después de 5 Minutos", "ss_15min": "Después de 15 Minutos",
        "ss_fixed": "Fijo", "ss_30sec": "Cada 30 Seg.", "ss_1min_rot": "Cada 1 Min.", "ss_5min_rot": "Cada 5 Min.",
        "layout_auto": "Automático", "layout_desktop": "1920x1080 o sup.",
        "layout_laptop": "1366x768 (Tablet Horiz.)", "layout_tablet": "800x1280 (Tablet Vert.)", "layout_mobile": "Smartphone",
        "hint_moode": "* Déjalo en blanco para usar la IP actual. Se abrirá al hacer clic en la carátula.",
        "hint_ws": "* Por defecto apunta a la dirección del rack. Modifícalo si CamillaDSP usa otra IP o puerto.",
        "hint_stream": "* URL del servidor HTTP de MPD para escuchar el audio en el dispositivo.",
        "ss_hint": "Toca para salir, Desliza para cambiar VU Meter",
        "tip_repeat": "Repetir", "tip_prev": "Anterior", "tip_next": "Siguiente", "tip_random": "Aleatorio", 
        "tip_stream": "Escuchar en el dispositivo", "tip_queue": "Ir a la Cola", "tip_mute": "Silenciar / Activar sonido",
        "tip_moode": "Abrir interfaz oficial moOde Audio", "tip_sync": "Sincronizar Archivo con MPD",
        "tip_change_view": "Cambiar Vista", "tip_add_queue": "Añadir a la cola",
        "tip_listen": "Escuchar", "tip_favorites": "Favoritos", "tip_edit": "Editar",
        "tip_delete": "Eliminar", "tip_dsp_pause": "Pausa o detiene la música para activar/desactivar el DSP.",
        "lbl_mini_player_ss": "Mostrar Mini Reproductor en el Salvapantallas",
        "tip_exit_ss": "Salir del Salvapantallas",
        "alpha_all": "Todos",
        "hdr_defaults": "Establecer Valores Predeterminados",
        "desc_defaults": "Configura los valores iniciales asignados automáticamente a cualquier dispositivo nuevo.",
        "lbl_vu_style_def": "Modelo de VU Meter Predeterminado (Tema)",
        "lbl_layout_def": "Resolución y Adaptación de Pantalla (Player)",
        "lbl_ss_timeout_def": "Tiempo de espera del Salvapantallas",
        "lbl_ss_random_def": "Rotación de Estilos Aleatoria",
        "btn_save_defaults": "Guardar como Predeterminado para Nuevos Clientes",
        "hdr_diagnostics": "Diagnóstico de la API Bridge",
        "btn_run_tests": "Ejecutar de Nuevo"
    },
    fr: {
        "tab_player": "Lecteur", "tab_queue": "File d'attente", "tab_favs": "Favoris",
        "tab_playlists": "Listes", "tab_webradio": "Radio", "tab_folders": "Fichiers",
        "tab_albums": "Albums", "tab_artists": "Artistes", "tab_search": "Rechercher", "tab_settings": "Paramètres",
        "title_queue_play": "File d'attente de lecture", "title_playlists_saved": "Vos listes de lecture enregistrées",
        "title_new_radio": "Configurer une nouvelle Web Radio",
        "hdr_lang": "Langue", "hdr_conn": "Connexion & Intégration",
        "hdr_screen": "Gestion de l'économiseur d'écran", "hdr_layout": "Apparence & Disposition",
        "hdr_dsp": "DSP & Traitement Audio", "hdr_smart_home": "Smart Home (HA / Alexa)",
        "hdr_appearance": "Apparence & Économiseur",
        "hdr_backup": "Sauvegarde & Restauration",
        "hw_bass": "BASSES", "hw_treble": "AIGUS", "hw_volume": "VOLUME",
        "lbl_camilladsp": "CamillaDSP (Stack)", "desc_camilladsp": "Activer/désactiver le traitement audio",
        "desc_smart_home": "Utilisez ces points de terminaison dans vos rest_command de Home Assistant pour contrôler le rack par la voix.",
        "lbl_endpoint_search": "Endpoint Recherche Vocale et Play", "lbl_endpoint_camilla": "Endpoint CamillaDSP ON/OFF",
        "item_folder": "Dossier", "item_track": "Piste", "item_playlist": "Liste de lecture",
        "item_album": "Album", "item_artist": "Artiste", "item_root": "Racine",
        "item_webradio_custom": "Web Radio (Personnalisée)", "hdr_webradio_moode": "Web Radio moOde", 
        "hdr_webradio_recent": "Radio Browser (Récents)", "hdr_webradio_custom": "Stations Personnalisées",
        "msg_added_queue": "Ajouté à la file d'attente !", "msg_playing": "Lecture en cours...",
        "msg_sync_ok": "Synchronisation terminée avec succès !", "msg_waiting": "En attente de connexion...",
        "msg_unknown": "Inconnu", "msg_loading": "Chargement en cours...", "msg_empty": "Aucun élément trouvé.",
        "prompt_playlist_name": "Nom de la liste :", "msg_playlist_saved": "Liste de lecture enregistrée !",
        "confirm_delete_playlist": "Supprimer la liste de lecture", "msg_fill_required": "Veuillez remplir au moins le nom et l'URL",
        "confirm_delete_radio": "Voulez-vous supprimer", "msg_sys_error": "Erreur lors de l'exécution de la commande système.",
        "confirm_sync": "Lancer la synchronisation ?", "msg_error": "Erreur.",
        "msg_error_prefix": "ERREUR : ", "msg_php_error": "ERREUR PHP",
        "msg_stream_url_missing": "Définissez l'URL de streaming HTTP dans les Paramètres !",
        "msg_stream_error": "Impossible de se connecter au flux : ", "confirm_clear_queue": "Vider la file d'attente ?",
        "msg_network_error": "Erreur Réseau : Station inaccessible",
        "msg_offline": "Hors ligne - Pas de réseau",
        "sync_title": "Synchronisation en cours...", "sync_desc1": "Analyse de l'archive et des pochette sur le serveur.",
        "sync_desc2": "Cette opération peut prendre quelques minutes.",
        "btn_sync": "Synchroniser", "btn_save_playlist": "Enregistrer la liste", "btn_clear": "Vider",
        "btn_save": "Enregistrer", "btn_up": "Haut", "btn_back": "Retour", "btn_search": "RECHERCHER",
        "btn_space": "ESPACE", "btn_test_ss": "Tester l'économiseur", "btn_close_moode": "Retour au Rack",
        "btn_play": "Lecture",
        "btn_export": "Exporter Config", "btn_import": "Importer Config",
        "desc_backup": "Enregistrez vos radios, favoris et paramètres dans un fichier local.",
        "lbl_config_radio": "Configurer une nouvelle Web Radio", "lbl_radio_name": "Nom de la station", 
        "lbl_radio_url": "URL du flux", "lbl_radio_logo": "URL du logo (Optionnel)", "lbl_custom_radios": "Vos Web Radios",
        "ph_radio_name": "ex. Radio Paradise", "ph_radio_url": "ex. http://stream.radioparadise.com/flac",
        "ph_radio_logo": "ex. https://.../logo.png", "ph_moode_url": "ex. http://192.168.1.50",
        "ph_ws_uri": "ex. ws://192.168.1.50:1234", "ph_stream_url": "ex. http://192.168.1.50:8000/mpd.ogg",
        "lbl_search_engine": "Moteur de recherche", "search_any": "Chercher partout", 
        "search_title": "Pistes uniquement (Titre)", "search_album": "Albums uniquement", "search_artist": "Artistes uniquement",
        "search_genre": "Genre uniquement", "search_file": "Dossiers/Chemins uniquement", "search_radio": "Radio uniquement",
        "lbl_settings_sys": "Panneau de contrôle et intégrations", "lbl_lang_select": "Langue de l'interface",
        "lbl_moode_url": "URL de l'interface moOde Audio", "lbl_ws_uri": "URI WebSocket CamillaDSP",
        "lbl_stream_url": "URL du flux local (moOde HTTP)", "lbl_ss_timeout": "Lancement de l'économiseur",
        "lbl_ss_random": "Rotation des styles", "lbl_vu_style": "Modèle de VU-mètre (Thème global)",
        "lbl_device_layout": "Adaptation de l'écran", "lbl_extra_options": "Options d'interface et graphiques", 
        "lbl_show_inline_vu": "VU-mètre dans le lecteur", "lbl_backlight": "Rétroéclairage du panneau", 
        "lbl_local_analyzer": "Analyseur audio local",
        "lbl_keep_ss_style": "Garder le thème rotatif à la sortie du SS",
        
        "vu_blue_mod70": "Blue Classic Mod. 70",
        "vu_blue_mono_mod1000": "Blue Mono Mod. 1000",
        "vu_champagne_mod73": "Champagne Gold Mod. 73",
        "vu_vfd_mod85": "VFD Peak Mod. 85",
        "vu_vintage_mod60": "Studio Vintage Mod. 60",
        "vu_waves_mod99": "Waves Studio Mod. 99",
        "vu_studio_mod77": "Studio Master Mod. 77",
        "vu_dark_meter_mod88": "Dark Meter Mod. 88",
        "vu_british_mod90": "British Console Mod. 90",
        "vu_light_meter_mod88": "Light Meter Mod. 88",
        "vu_cyan_meter_mod88": "Cyan Meter Mod. 88",
        "vu_neon_mod95": "Neon Cyan Mod. 95",
        "vu_minimal_mod00": "Minimal Dark Mod. 00",
        "vu_orange_mod70": "Warm Orange Mod. 70",
        "vu_tube_mod50": "Blue Tube Mod. 50",
        "vu_flat_mod00": "Minimal Flat Mod. 00",
        "vu_touch_mod15": "Touch VU Mod. 15",
        "vu_amber_mod75": "Amber Classic Mod. 75",

        "ss_disabled": "Désactivé", "ss_1min": "Après 1 minute", "ss_5min": "Après 5 minutes", "ss_15min": "Après 15 minutes",
        "ss_fixed": "Fixe", "ss_30sec": "Toutes les 30 sec.", "ss_1min_rot": "Toutes les 1 min.", "ss_5min_rot": "Toutes les 5 min.",
        "layout_auto": "Automatique", "layout_desktop": "1920x1080 ou sup.",
        "layout_laptop": "1366x768 (Tablette Horiz.)", "layout_tablet": "800x1280 (Tablette Vert.)", "layout_mobile": "Smartphone",
        "hint_moode": "* Laisser vide pour utiliser l'IP actuelle. S'ouvrira en cliquant sur la pochette.",
        "hint_ws": "* Pointe par défaut vers l'adresse du rack. À modifier si CamillaDSP utilise une autre IP/port.",
        "hint_stream": "* URL du serveur HTTP MPD pour écouter l'audio sur l'appareil.",
        "ss_hint": "Appuyer pour quitter, Glisser pour changer de VU-mètre",
        "tip_repeat": "Répéter", "tip_prev": "Précédent", "tip_next": "Suivant", "tip_random": "Aléatoire", 
        "tip_stream": "Écouter sur l'appareil", "tip_queue": "Aller à la file d'attente", "tip_mute": "Muet / Activer le son",
        "tip_moode": "Ouvrir l'interface officielle moOde Audio", "tip_sync": "Synchroniser l'archive avec MPD",
        "tip_change_view": "Changer de vue", "tip_add_queue": "Ajouter à la file d'attente",
        "tip_listen": "Écouter", "tip_favorites": "Favoris", "tip_edit": "Modifier",
        "tip_delete": "Supprimer", "tip_dsp_pause": "Mettez en pause ou arrêtez la musique pour activer/désactiver le DSP.",
        "lbl_mini_player_ss": "Afficher le Mini Lecteur dans l'économiseur",
        "tip_exit_ss": "Quitter l'économiseur d'écran",
        "alpha_all": "Tous",
        "hdr_defaults": "Définir les Valeurs par Défaut",
        "desc_defaults": "Configurez les valeurs initiales attribuées automatiquement à tout nouvel appareil.",
        "lbl_vu_style_def": "Modèle de VU-mètre par Défaut (Thème)",
        "lbl_layout_def": "Résolution et Adaptation d'Écran (Lecteur)",
        "lbl_ss_timeout_def": "Délai de l'économiseur d'écran",
        "lbl_ss_random_def": "Rotation aléatoire des styles",
        "btn_save_defaults": "Enregistrer comme Défaut pour les Nouveaux Clients",
        "hdr_diagnostics": "Diagnostics de l'API Bridge",
        "btn_run_tests": "Exécuter à Nouveau"
    }
};
